(() => {
 if(window.top!==window || document.querySelector('spendshield-live'))return;
 const api=async(op,body,extra={})=>{const r=await chrome.runtime.sendMessage({op,body,...extra});if(!r?.ok)throw Error(r?.error||'SpendShield unavailable');return r.data;};
 const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0);
 const time=iso=>{const m=Math.max(0,Math.ceil((Date.parse(iso)-Date.now())/60000));return `${Math.floor(m/60)}h ${m%60}m`;};
 const bodyWasInert=document.body.inert;
 let lastScan=0;
 let host,root,panel,body,status,context,purchase,expanded=false,dismissed=false,blocked=false,busy=false,lastUrl=location.href,timer;
 const css=`:host{all:initial;font:14px/1.5 system-ui,sans-serif;color:#193c32;position:fixed;right:20px;bottom:20px;z-index:2147483647;max-width:calc(100vw - 24px)}*{box-sizing:border-box}button,input{font:inherit}button{cursor:pointer;border:1px solid #c9d8cf;border-radius:10px;padding:10px 14px;background:white;color:#214d3b;font-weight:650;text-align:left}button:hover{background:#edf4e9}button:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible{outline:3px solid #548d73;outline-offset:2px}.primary{background:#214d3b;color:white;border-color:#214d3b}.primary:hover{background:#316650}.panel{width:390px;max-width:calc(100vw - 24px);background:#fcfdf9;border:1px solid #d7e3d9;border-radius:20px;box-shadow:0 14px 60px #102d3330;overflow:hidden;animation:arrive .2s ease-out}header{display:flex;align-items:center;gap:8px;background:#edf3e8;padding:14px}header strong{flex:1}header button{padding:5px 9px}.body{padding:20px;max-height:75vh;overflow:auto}h2{font-size:22px;line-height:1.2;margin:0 0 12px}h3{margin:16px 0 8px}p{margin:10px 0}.muted{font-size:12px;color:#597066}.metric{font-size:32px;font-weight:750;letter-spacing:-1px}.actions{display:grid;gap:8px;margin-top:16px}.row{display:flex;justify-content:space-between;gap:12px;margin:8px 0}.row strong{text-align:right}label{display:grid;gap:6px;margin:12px 0}input{min-width:0;width:100%;padding:10px;background:white;border:1px solid #bdcec2;border-radius:8px;color:#193c32}progress{width:100%;height:12px;accent-color:#527745}.error{color:#a53429}.success{border-radius:12px;background:#e8f1d8;padding:16px;animation:arrive .3s ease-out}.block{position:fixed;inset:0;background:#eaf0e8;display:grid;place-items:center;padding:20px;overflow:auto}.block .panel{width:440px}.collapsed{box-shadow:0 8px 30px #193c3225}.notice{font-size:12px;padding:8px;border-radius:8px;background:#fff3d9}@keyframes arrive{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}`;
 function el(tag,text,cls,parent=body){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;parent?.append(n);return n;}
 function button(text,fn,parent=body,cls=''){const b=el('button',text,cls,parent);b.type='button';b.onclick=async()=>{if(busy)return;busy=true;b.disabled=true;try{await fn();}catch(e){el('p',e.message,'error');}finally{busy=false;b.disabled=false;}};return b;}
 function row(label,value){const r=el('div',undefined,'row');el('span',label,'',r);el('strong',value,'',r);}
 function field(label,value,type='text'){const l=el('label',label);const n=el('input',undefined,'',l);n.type=type;n.value=value||'';if(type==='number'){n.min='0.01';n.step='0.01';}return n;}
 function mount(){if(host)return;host=document.createElement('spendshield-live');root=host.attachShadow({mode:'closed'});el('style',css,'',root);document.documentElement.append(host);}
 function frame(title){document.body.inert=blocked||bodyWasInert;mount();while(root.children.length>1)root.lastChild.remove();const wrap=blocked?el('div',undefined,'block',root):root;panel=el('section',undefined,'panel',wrap);panel.setAttribute('aria-label','SpendShield Live');const h=el('header',undefined,'',panel);el('strong','◈ SpendShield Live','',h);if(!blocked){button('−',()=>{expanded=false;renderCollapsed();},h).setAttribute('aria-label','Minimize SpendShield');button('×',()=>{dismissed=true;host.remove();host=null;},h).setAttribute('aria-label','Dismiss SpendShield');}body=el('div',undefined,'body',panel);el('h2',title);}
 function renderCollapsed(){if(dismissed||blocked)return;mount();while(root.children.length>1)root.lastChild.remove();button('◈ SpendShield · '+(context.page_type==='gambling'?'Your chosen safeguards':`Check ${context.price?money(Number(context.price)):'this purchase'}`),()=>open(),root,'collapsed');}
 function goal(s){el('h3',s.goal.name);row('Saved',money(s.goal.saved)+' / '+money(s.goal.target));const bar=el('progress');bar.max=100;bar.value=s.goal.progress;bar.setAttribute('aria-label','Savings goal progress');if(s.goal.planned){row('Protected, not yet confirmed saved',money(s.goal.planned));row('If these intentions are saved',money(s.goal.planned_saved)+' / '+money(s.goal.target));const planned=el('progress');planned.max=100;planned.value=s.goal.planned_progress;planned.setAttribute('aria-label','Goal including protected intentions');}}
 async function open(){expanded=true;if(context.page_type==='gambling')return guard();frame('Check the purchase');el('p','Confirm the total before viewing your tradeoff. No page context is sent to Gemini unless analysis is requested or automatic analysis is enabled.','muted');let c=context;
 if(c.confidence<.85){el('p','Interpreting relevant product details…','muted');c=await api('classify',{...c,explicit:true});context=c;}
 frame('Check the purchase');el('p',c.interpretation||'Extracted from product metadata. Please check the total.','muted');const name=field('Product or cart',c.product_name);const amount=field('Confirmed total (USD)',c.currency==='USD'?c.price:'','number');if(c.currency && c.currency!=='USD')el('p','This page uses another currency. SpendShield supports USD only; no exchange rate is assumed.','notice');button('Show my tradeoff',async()=>{const price=SpendShieldExtract.price(amount.value);if(!price)throw Error('Enter a positive USD amount with at most two decimals.');context={...c,product_name:name.value,price,currency:'USD'};const data=await api('analyze',context);purchase=data.purchase;status=data.status;showPurchase();},body,'primary');}
 function showPurchase(){frame('Here’s the tradeoff');el('p',purchase.product_name);el('div',money(purchase.detected_price),'metric');const i=purchase.impact;row('Remaining discretionary budget',money(i.available));row('This purchase would use',i.budget_percent===null?'No remaining budget':i.budget_percent+'%');goal(status);row('Buy now',i.buying_days===null?'No projection':i.buying_days+' days to goal');row('Skip',i.baseline_days===null?'No projection':i.baseline_days+' days to goal');if(i.delay_days!==null)row('Difference',i.delay_days+' days');el('p','Scenario: buying diverts this amount from planned savings. Projections depend on your recorded finances.','muted');
 if(purchase.resolved){el('p','This decision is already recorded. Review or undo it in SpendShield Activity.','notice');button('Open SpendShield',()=>api('open'));return;}
 if(purchase.wait_until&&Date.parse(purchase.wait_until)>Date.now())el('p','You chose to wait before buying this. Remaining: '+time(purchase.wait_until),'notice');
 const a=el('div',undefined,'actions');button('Protect this money',()=>protect('purchase_skipped'),a,'primary');button('Find a cheaper option',alternatives,a);if(purchase.wait_until&&Date.parse(purchase.wait_until)>Date.now())button('Continue waiting',()=>{expanded=false;renderCollapsed();},a);else button('Wait '+(status.settings.wait_hours||24)+' hours',async()=>{purchase={...purchase,...await api('wait',{purchase_id:purchase.id})};showPurchase();},a);button('Continue anyway',()=>{dismissed=true;host.remove();host=null;},a);}
 async function protect(action,extra={}){const result=await api('protect',{purchase_id:purchase.id,action,...extra});status=result.status;frame('A little more room for your goal');const s=el('div',undefined,'success');el('div',money(result.protected)+' protected','metric',s);el('p',result.message,'',s);goal(status);row('Money Rescued this month',money(status.money_rescued));button('View my goal',()=>api('open'),body,'primary');}
 function alternatives(){frame('Choose a lower-cost option');el('p','Only record a price you verified. Search results are not verified retailer offers.','muted');button('Search the web for alternatives',()=>{window.open('https://www.google.com/search?q='+encodeURIComponent(purchase.product_name+' cheaper alternative'),'_blank','noopener,noreferrer');});if(status.demo){el('p','DEMO CATALOG RESULT · fictional, not a retailer offer','notice');for(const option of purchase.alternatives||[])button(option.name+' · '+money(option.price)+' · protect '+money(option.savings),()=>protect('cheaper_alternative_selected',{alternative_id:option.id,demo_alternative:true}),body,'primary');}const name=field('Alternative you found','');const amount=field('Actual lower price (USD)','','number');button('Record the difference',()=>{if(!name.value.trim())throw Error('Name the alternative first.');return protect('cheaper_alternative_selected',{alternative_name:name.value,alternative_price:amount.value});});button('Back to tradeoff',()=>showPurchase());}
 function cachedBlock(s){if(!s?.settings?.guard_enabled||!s.settings.shield_enabled)return false;const g=s.guard;const weekEnd=new Date(g.week_start+'T00:00:00');weekEnd.setDate(weekEnd.getDate()+7);const sameWeek=Date.now()<weekEnd.getTime();return (s.settings.block_cooldown && Date.parse(g.cooldown_until)>Date.now()) || (s.settings.block_limit && g.spent>=g.limit && sameWeek);}
 async function guard(){try{status=await api('status',undefined,{proposed:'30'});blocked=status.blocked&&context.confidence>=.85;}catch(e){blocked=cachedBlock(status)&&context.confidence>=.85;if(!blocked){frame('SpendShield unavailable');el('p','Your spending tools could not connect. You can dismiss this panel and keep browsing.');return;}}
 frame(blocked?'Shield Mode is on':'Your chosen gambling limit');if(blocked)el('p','You asked SpendShield to cover gambling pages while your safeguard applies. You can change this in settings.');row('Weekly limit',money(status.guard.limit));row('Recorded this week',money(status.guard.spent));row('Remaining',money(status.guard.remaining));if(status.guard.cooldown_until&&Date.parse(status.guard.cooldown_until)>Date.now())row('Cooldown remaining',time(status.guard.cooldown_until));
 const amount=field('Amount you are considering (USD)','30','number');el('p','Enter an amount here; SpendShield does not read the site’s wager or payment fields.','muted');const preview=el('div');const update=async()=>{const value=SpendShieldExtract.price(amount.value);if(!value)throw Error('Enter a positive USD amount.');status=await api('status',undefined,{proposed:value});preview.textContent=status.guard.over_by>0?`This would exceed your chosen weekly limit by ${money(status.guard.over_by)}.`:'This amount is within your recorded weekly limit. This is not a recommendation to gamble.';if(status.guard.impact.delay_days!==null)preview.textContent+=' Savings-goal scenario: '+status.guard.impact.delay_days+(status.guard.impact.delay_days===1?' additional day.':' additional days.');};button('Check this amount',update);await update().catch(()=>{el('p','Offline safeguard: last known settings. Live calculations need the backend.','notice');});
 const a=el('div',undefined,'actions');button('Put this amount toward my goal instead',async()=>{const value=SpendShieldExtract.price(amount.value);if(!value)throw Error('Enter a positive USD amount.');const result=await api('analyze',{...context,product_name:'Money redirected instead of gambling',price:value,currency:'USD'});purchase=result.purchase;await protect('money_redirected_to_goal');},a,'primary');button('Start 24-hour cooldown',async()=>{status=await api('cooldown',{enable_shield:false});await guard();},a);button('Start 24-hour Shield Mode',async()=>{status=await api('cooldown',{enable_shield:true});blocked=true;await guard();},a);button('Review spending / view my goal',()=>api('open'),a);button('Disable Shield Mode / settings',()=>api('options'),a);if(!blocked)button('Continue anyway',()=>{dismissed=true;host.remove();host=null;},a);el('p','Voluntary browser cover, not a payment block. No money is transferred. Support is available in SpendShield Gambling Guard.','muted');}
 async function inspect(explicit=false){if(dismissed&&!explicit)return;if(!explicit&&Date.now()-lastScan<10000)return;lastScan=Date.now();const cfg=await api('config');context=SpendShieldExtract.extract(document,location.href,cfg.cached?.settings?.domains||['draftkings.com','fanduel.com','betmgm.com','bet365.com']);if(context.page_type==='unrelated'&&!explicit)return;
 try{status=await api('status');}catch{status=cfg.cached;if(!status){frame('SpendShield unavailable');el('p','Open the extension settings to pair your local app.');return;}}
 if(context.page_type==='gambling'){if(!status.settings.guard_enabled&&!explicit)return;if(context.confidence<.85){try{context=await api('classify',context);}catch{}if(context.page_type!=='gambling')return;if(context.confidence<.85){if(explicit)await guard();else renderCollapsed();return;}}blocked=status.blocked||cachedBlock(status);if(blocked||explicit)await guard();else renderCollapsed();return;}
 if(!status.settings.purchase_enabled&&!explicit)return;
 if(context.page_type==='unrelated')context.explicit=true;
 if(status.settings.auto_analyze&&context.confidence<.85){context=await api('classify',context);if(context.page_type==='unrelated')return;}
 renderCollapsed();if(explicit)await open();}
 chrome.runtime.onMessage.addListener((m)=>{if(m.op==='inspect'){dismissed=false;void inspect(true).catch(()=>{});}});
 chrome.storage.onChanged.addListener((changes)=>{if(changes.cached&&host&&context?.page_type==='gambling'){const next=changes.cached.newValue;if(next && !next.settings.shield_enabled && blocked){blocked=false;void guard().catch(()=>{});}}});
 void inspect().catch(()=>{});
 const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(location.href!==lastUrl){lastUrl=location.href;lastScan=0;dismissed=false;blocked=false;host?.remove();host=null;void inspect().catch(()=>{});}else if(!host&&!dismissed)void inspect().catch(()=>{});},1200);});
 observer.observe(document.documentElement,{childList:true,subtree:true});
 setInterval(()=>{if(blocked&&!document.hidden)void guard().catch(()=>{});},60000);
})();
